FROM openjdk:16-jdk
COPY ./*.jar app.jar
ARG MONGO_URL_ARG=$MONGO_URL
ARG SECRET_KEY_ARG=$SECRET_KEY_ARG

CMD echo $MONGO_URL_ARG

ENV MONGO_URL $MONGO_URL_ARG
ENV SECRET_KEY $SECRET_KEY_ARG
ENTRYPOINT ["java", "-jar", "/app.jar"]