spring:
  rabbitmq:
    host: localhost
    port: 5672

  data:
    mongodb:
      auto-index-creation: true
      authentication-database: admin
      repositories:
        type: reactive
      uri: ${MONGO_URL}

  rsocket:
    server:
      transport: websocket
      port: 7000
      mapping-path: /rsocket

jwt:
  secret: ${SECRET_KEY:testtesttesttesttesttesttesttest}